app:
  baseUrl: http://localhost:8880
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:common/db/migration,classpath:dev/db/migration
logging:
  level:
    com.smartvizz.erp.backend: DEBUG
jwt:
  secret: G2RsbDddUnJfXG8i4FqKMvMm1C9eJ8VRg9YWZlNfY4=
  expiration: 3600000  #1 hour in milliseconds